#!/bin/sh
export CARPOOL_LOGISTICS_GOOGLEMAPS_KEY=$CPL_GM_KEY
export CARPOOL_LOGISTICS_SERVER_PORT=$CPL_SERVER_PORT
export CARPOOL_LOGISTICS_SERVER_PATH=$CPL_SERVER_PATH
export CARPOOL_LOGISTICS_DB_URL=$CPL_DB_URL
export CARPOOL_LOGISTICS_DB_USERNAME=$CPL_DB_USER
export CARPOOL_LOGISTICS_DB_PASSWORD=$CPL_DB_PASS

java -Djava.security.egd=file:/dev/./urandom -jar /app.jar